version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../dev/backend.Dockerfile
    container_name: finance-backend
    env_file:
      - ../dev/.env.example
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../frontend
      dockerfile: ../dev/frontend.Dockerfile
    container_name: finance-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
